FROM golang:1.15-alpine as build

RUN apk update && apk upgrade && apk add --update alpine-sdk && \
    apk add --no-cache git make

WORKDIR ./src/github.com/devchallenge/stock-service

COPY . ./

RUN make build lint test
